import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

const maisonNeueExtendedBook = localFont({
  src: "../fonts/MaisonNeue-ExtendedBook.woff2",
  variable: "--font-maison-neue-extended-book",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${maisonNeueExtendedBook.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
